version: 2
jobs:
  build_dist:
    docker:
      - image: circleci/openjdk:11-stretch

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run:
          name: Create distribution
          command: |
              gradle distTar
              mv build/distributions/bluestone*.tar /tmp/bluestone.tar

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: /tmp/bluestone.tar
          destination: bluestone.tar

  build_jar:
    docker:
      - image: circleci/openjdk:11-stretch

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run:
          name: Create shadow JAR
          command: |
              gradle shadowJar
              mv build/libs/bluestone*-all.jar /tmp/bluestone.jar

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: /tmp/bluestone.jar
          destination: bluestone.jar

workflows:
    version: 2
    build:
        jobs:
            - build_dist
            - build_jar
